/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlelab;

import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        // Create a DateTime object representing the current date and time
        DateTime now = DateTime.now();

        // Format the DateTime object using a specific pattern
        DateTimeFormatter formatter = DateTimeFormat.forPattern("yyyy-MM-dd HH:mm:ss");
        String formattedDateTime = formatter.print(now);

        // Print the formatted date and time
        System.out.println("Current date and time: " + formattedDateTime);

        System.out.println(new App().getGreeting());
    }
}
